services:
  frontend:
    image: nginx:alpine
    container_name: helicorp_frontend_app
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "127.254.99.100:80:80"
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: helicorp_backend_api
    ports:
      - "127.254.99.101:80:3000"
    environment:
      - NODE_ENV=production
    restart: always